### ISSUE TITLE
Error running docker compose up using the branch blaze_update

### ISSUE THREAD

**Issue by RaffaelBild** [medizininformatik-initiative/Projectathon6-miracum1#22]
Hello,

unfortunately, I'm getting an error when I try to run the command `docker compose up` using the branch `blaze_update` in the folder step2. The output I get is as follows:

step2-projectathon6-miracum1-step2-1  | OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
step2-projectathon6-miracum1-step2-1  | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
step2-projectathon6-miracum1-step2-1  | OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
step2-projectathon6-miracum1-step2-1  | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
step2-projectathon6-miracum1-step2-1  | OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
step2-projectathon6-miracum1-step2-1  | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
step2-projectathon6-miracum1-step2-1  | During startup - Warning messages:
step2-projectathon6-miracum1-step2-1  | 1: package ‘utils’ in options("defaultPackages") was not found
step2-projectathon6-miracum1-step2-1  | 2: package ‘stats’ in options("defaultPackages") was not found
step2-projectathon6-miracum1-step2-1  | Error: .onLoad failed in loadNamespace() for 'utils', details:
step2-projectathon6-miracum1-step2-1  |   call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
step2-projectathon6-miracum1-step2-1  |   error: cannot popen '/usr/bin/which 'uname' 2>/dev/null', probable reason 'Cannot allocate memory'
step2-projectathon6-miracum1-step2-1  | Execution halted
step2-projectathon6-miracum1-step2-1 exited with code 1

The OS of the machine used is Ubuntu 20.04.5 LTS and the version of Docker is 20.10.7, build f0df350

Any help would be greatly appreciated

**Comment by mematt** [comment]
Hi, 

1. is there a way to just update to a newer docker version? 
Searching for "docker compose up OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted" gave these two somewhat similar problems. 

- [Unable to start label studio from latest docker due to OpenBLAS operation not permitted ](https://github.com/heartexlabs/label-studio/issues/3070) 
- [One solution hier suggests updating to docker v.20.10.12](https://github.com/heartexlabs/label-studio/issues/3070#issuecomment-1283671333)
- In the docker file, we limit nCPU similarly to 1 thread  `## build ARGs ARG NCPUS=${NCPUS:--1}`. 
- Also, would it be possible to try pulling the [docker hub version of the blaze container as described in step1](https://github.com/medizininformatik-initiative/Projectathon6-miracum1#a-image-von-dockerhub-ziehen-1) only changing the git clone path for the` blaze branch`

2. Additionally, there are some packages which do not seem to install correctly. It might also be an issue with the proxy settings and internet connection.  

if needed, we can setup a debugging call for the next week.

**Comment by NandhiniS08** [comment]
In the error messgae, there is also a memory related issue   _error: cannot popen '/usr/bin/which 'uname' 2>/dev/null', probable reason 'Cannot allocate memory'_
Is it possible to increase the RAM in the server you are executing?

**Comment by RaffaelBild** [comment]
Thanks for the support!
I have tried this again on a different VM with docker version 20.10.23 installed and it seems this has fixed the problem :)
